/**
 * certificateTemplate.js
 *
 * Generates a Diploma / Statement-of-Marks certificate as HTML and PDF,
 * using Blue.png as the certificate background/border, replicating the
 * layout of DIPLOMA_CERTIFICTAE.docx.
 *
 * Usage:
 *   const { generateCertificatePDF } = require('./certificateTemplate');
 *
 *   await generateCertificatePDF(studentData, '/path/to/Blue.png', '/path/to/output.pdf');
 *
 * studentData shape (matches the CSV template fields):
 * {
 *   rollNo, candidateName, fatherName, courseName, semester, part,
 *   examSession, examFlag, academicYear, dateOfResult,
 *   certificateNumber,               // unique cert no, generated by caller
 *   papers: [                        // exactly 6 entries expected
 *     { code, name, ia, th, prpw, result },
 *     ...
 *   ],
 *   totalMax, totalObtained, division
 * }
 */

const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');

// ---------- helpers ----------

/** Reads Blue.png from disk and returns a base64 data-URI so the HTML is self-contained. */
function imageToDataUri(imagePath) {
  const ext = path.extname(imagePath).slice(1) || 'png';
  const buffer = fs.readFileSync(imagePath);
  return `data:image/${ext};base64,${buffer.toString('base64')}`;
}

/** Renders a mark cell; blank/undefined marks are shown as "-" (not "0" or "N/A"). */
function fmtMark(val) {
  if (val === undefined || val === null || val === '') return '-';
  return String(val);
}

/** Escapes basic HTML special chars in user-supplied text fields. */
function esc(str) {
  if (str === undefined || str === null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/** Builds the 6 subject rows of the marks table. */
function buildPaperRows(papers = []) {
  const rows = [];
  for (let i = 0; i < 6; i++) {
    const p = papers[i] || {};
    rows.push(`
      <tr>
        <td class="sr">${i + 1}.</td>
        <td class="code">${esc(p.code)}</td>
        <td class="name">${esc(p.name)}</td>
        <td class="sem">${esc(p.sem || '')}</td>
        <td class="mark">${fmtMark(p.ia)}</td>
        <td class="mark">${fmtMark(p.th)}</td>
        <td class="mark">${fmtMark(p.prpw)}</td>
        <td class="result">${esc(p.result || '')}</td>
      </tr>`);
  }
  return rows.join('\n');
}

// ---------- main HTML builder ----------

function fontToDataUri(fontPath) {
  try {
    const buffer = fs.readFileSync(fontPath);
    return `data:font/ttf;base64,${buffer.toString('base64')}`;
  } catch(e) {
    console.error("Font not found at", fontPath);
    return '';
  }
}

/**
 * Builds the full certificate HTML string for one student.
 * @param {Object} data       Student/certificate data (see file header).
 * @param {string} bgImagePath Absolute path to Blue.png.
 */
function generateCertificateHTML(data, bgImagePath) {
  const bgDataUri = imageToDataUri(bgImagePath);
  const logoPath = path.join(path.dirname(bgImagePath), 'VMI Logo.png');
  let logoDataUri = '';
  try {
    logoDataUri = imageToDataUri(logoPath);
  } catch (e) {
    console.error("VMI Logo not found at", logoPath);
  }

  const fontPath = path.join(path.dirname(bgImagePath), 'fonts', 'oldenglishtextmt.ttf');
  const fontDataUri = fontToDataUri(fontPath);

  let signatureDataUri = '';
  if (data.signatureImage && fs.existsSync(data.signatureImage)) {
    try {
      signatureDataUri = imageToDataUri(data.signatureImage);
    } catch (e) {
      console.error("Signature image failed to convert:", e.message);
    }
  }

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Statement of Marks - ${esc(data.rollNo)}</title>
<style>
  @page { size: A4; margin: 0; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: 'Tahoma', sans-serif;
    font-size: 10pt;
    color: #1a1a1a;
    width: 210mm;
    height: 297mm;
    overflow: hidden;
    position: relative;
    background-image: url('${bgDataUri}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
  }
  .content {
    position: relative;
    padding: 22mm 15mm 10mm 15mm;
    height: 297mm;
    display: flex;
    flex-direction: column;
  }
  .cert-no {
    position: absolute;
    top: 22mm;
    right: 15mm;
    font-size: 9pt;
    color: #0f4c75;
    font-weight: 700;
    text-align: right;
    line-height: 1;
  }
  .header {
    text-align: center;
    margin-bottom: 8mm;
    padding-left: 24mm;
    padding-right: 24mm;
  }
  .header h1 {
    font-family: 'Old English Text MT', serif;
    color: #0f4c75;
    font-size: 20pt;
    margin: 1mm 0 0.5mm 0;
    letter-spacing: 0.3pt;
    font-weight: normal;
  }
  .header .sub {
    color: #0f4c75;
    font-size: 10pt;
    font-weight: 600;
    margin: 0;
  }
  .rule {
    border-top: 1.5pt solid #0f4c75;
    margin: 2mm 0;
  }
  .title {
    text-align: center;
    color: #b3261e;
    font-size: 12pt;
    font-weight: 700;
    letter-spacing: 1pt;
    margin: 1.5mm 0 3mm 0;
    border-top: 1pt solid #0f4c75;
    border-bottom: 1pt solid #0f4c75;
    padding: 1.5mm 0;
  }

  .info-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 2.5mm;
    font-size: 10pt;
  }
  .info-table td {
    padding: 0.6mm 2mm;
    vertical-align: top;
  }
  .info-table td.label {
    font-weight: 600;
    width: 45mm;
  }
  .info-table td.colon {
    width: 4mm;
  }

  table.marks {
    width: 100%;
    border-collapse: collapse;
    font-size: 10pt;
    margin-bottom: 2.5mm;
  }
  table.marks th, table.marks td {
    border: 0.75pt solid #4a6fa5;
    padding: 1mm 1.5mm;
    text-align: center;
  }
  table.marks th {
    background: rgba(74, 111, 165, 0.15);
    font-weight: 700;
    color: #0f4c75;
  }
  table.marks td.name { text-align: left; }

  table.summary {
    width: 100%;
    border-collapse: collapse;
    font-size: 10pt;
    margin-bottom: 2.5mm;
  }
  table.summary th, table.summary td {
    border: 0.75pt solid #4a6fa5;
    padding: 1.5mm;
    text-align: center;
  }
  table.summary th {
    background: rgba(74, 111, 165, 0.15);
    color: #0f4c75;
  }

  .decl-row {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    font-size: 10pt;
    margin: 3mm 0 2mm 0;
  }
  .decl-date {
    font-weight: 700;
    padding-top: 2mm;
  }
  .sign-block {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 60mm;
  }
  .sign-box {
    width: 55mm;
    height: 20mm;
    margin-bottom: 1mm;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
  }
  .sign-box img {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
  }
  .sign-label {
    font-weight: 700;
    font-size: 10pt;
  }

  .notes {
    font-size: 10pt;
    line-height: 1.35;
    margin-top: 2mm;
  }
  .notes b { color: #000; }
  .notes ol { margin: 0.5mm 0 0 4mm; padding: 0; }
  .notes li { margin-bottom: 0.5mm; }

  .footer-verify {
    margin-top: 3mm;
    font-size: 10pt;
    color: #555;
    text-align: center;
    border-top: 0.5pt solid #aaa;
    padding-top: 1.5mm;
  }
</style>
</head>
<body>
  <div class="content">

    ${logoDataUri ? `<img src="${logoDataUri}" style="position: absolute; top: 22mm; left: 16mm; width: 24mm; height: 24mm; object-fit: contain;" />` : ''}
    <div class="cert-no">${esc(data.certificateNumber)}</div>

    <div class="header">
      <h1>Varahamihira Multidisciplinary Institute</h1>
      <p class="sub">(${esc(data.semester)} Semester Exam, ${esc(data.examSession)})</p>
    </div>

    <div class="title">STATEMENT OF MARKS</div>

    <table class="info-table">
      <tr>
        <td class="label">Exam Roll Number</td><td class="colon">:</td><td>${esc(data.rollNo)}</td>
      </tr>
      <tr>
        <td class="label">Course Name</td><td class="colon">:</td><td>${esc(data.courseName)}</td>
      </tr>
      <tr>
        <td class="label">Semester</td><td class="colon">:</td><td>${esc(data.semester)}</td>
      </tr>
      <tr>
        <td class="label">Name of the Candidate</td><td class="colon">:</td><td>${esc(data.candidateName)}</td>
      </tr>
      <tr>
        <td class="label">Father's Name</td><td class="colon">:</td><td>${esc(data.fatherName)}</td>
      </tr>
    </table>

    <table class="marks">
      <thead>
        <tr>
          <th>Sr.<br>No.</th>
          <th>Paper<br>Code</th>
          <th>Paper Name</th>
          <th>Sem</th>
          <th>IA<br>(Obt/Max)</th>
          <th>TH<br>(Obt/Max)</th>
          <th>PR/PW<br>(Obt/Max)</th>
          <th>Paper Result</th>
        </tr>
      </thead>
      <tbody>
        ${buildPaperRows(data.papers)}
      </tbody>
    </table>

    <table class="summary">
      <tr>
        <th>Division</th><th>Grand Total Obtained</th><th>Grand Total Maximum</th>
      </tr>
      <tr>
        <td>${esc(data.division)}</td>
        <td>${esc(data.totalObtained)}</td>
        <td>${esc(data.totalMax)}</td>
      </tr>
    </table>

    <div class="decl-row">
      <span class="decl-date">Date of Result Declaration: ${esc(data.dateOfResult)}</span>
      <div class="sign-block">
        <div class="sign-box">
          ${signatureDataUri ? `<img src="${signatureDataUri}" alt="Signature" />` : ''}
        </div>
        <span class="sign-label">${esc(data.signatoryLabel || 'O.S.D. (Examination)')}</span>
      </div>
    </div>

    <div class="notes">
      <b>Passing criteria of a Paper (All conditions are necessary):</b><br>
      (i) 40% in TH; (ii) 40% in IA/PR (wherever applicable); and (iii) 40% in TH + IA/PR, taken together.<br><br>
      <b>Abbreviations:</b> AB: Absent; ER: Essential Repeat; F: Failed in Paper; F-PR: Failed in Practical;
      F-TH: Failed in Theory; IA: Internal Assessment; Imp: Improvement; Max: Maximum; Obt: Obtained;
      P: Passed in Paper; PR: Practical; PW: Practical Work; RL: Result will be declared later, if necessary; TH: Theory.<br><br>
      <b>Disclaimer:</b>
      <ol>
        <li>The result displayed on the Institute website is subject to correction if any discrepancy is subsequently noticed.</li>
        <li>This web-based Statement of Marks is valid for all official purposes. Students are advised to have this
          Statement of Marks duly authenticated by the Head/Principal of the concerned Department/Centre.</li>
        <li>Students should immediately contact the Examination Branch if there is any discrepancy in the above
          statement of marks or the prescribed passing criteria within one month from the date of declaration of the result.</li>
      </ol>
    </div>

    <div class="footer-verify">
      This certificate is digitally issued and printing it is invalid without the Institute hologram
    </div>

  </div>
</body>
</html>`;
}

// ---------- PDF rendering ----------

/**
 * Renders one certificate to a PDF file using Puppeteer.
 * @param {Object} data        Student/certificate data.
 * @param {string} bgImagePath Absolute path to Blue.png.
 * @param {string} outputPath  Where to write the resulting PDF.
 */
async function generateCertificatePDF(data, bgImagePath, outputPath) {
  const html = generateCertificateHTML(data, bgImagePath);

  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    await page.pdf({
      path: outputPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '0mm', bottom: '0mm', left: '0mm', right: '0mm' },
    });
  } finally {
    await browser.close();
  }
  return outputPath;
}

/**
 * Generates certificates for many students in one call.
 * @param {Object[]} studentsData Array of student data objects.
 * @param {string} bgImagePath    Absolute path to Blue.png.
 * @param {string} outDir         Directory to write PDFs into.
 * @returns {Promise<string[]>}   Array of generated file paths.
 */
async function generateBulkCertificates(studentsData, bgImagePath, outDir) {
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const outputPaths = [];
  try {
    for (const data of studentsData) {
      const html = generateCertificateHTML(data, bgImagePath);
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });

      const fileName = `${data.rollNo}_${(data.candidateName || '').replace(/\s+/g, '_')}_Diploma.pdf`;
      const outputPath = path.join(outDir, fileName);

      await page.pdf({
        path: outputPath,
        format: 'A4',
        printBackground: true,
        margin: { top: '0mm', bottom: '0mm', left: '0mm', right: '0mm' },
      });

      await page.close();
      outputPaths.push(outputPath);
    }
  } finally {
    await browser.close();
  }
  return outputPaths;
}

module.exports = {
  generateCertificateHTML,
  generateCertificatePDF,
  generateBulkCertificates,
};
